name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        
    - name: Cache Maven packages
      uses: actions/cache@v3
      with:
        path: ~/.m2
        key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
        restore-keys: ${{ runner.os }}-m2
        
    - name: Build and test with Maven
      run: |
        mvn clean compile test-compile
        mvn test -Dtest=!GitLabTestcontainersTest
        mvn surefire-report:report-only
        
    - name: Generate comprehensive test report
      run: |
        mvn surefire-report:report
        mvn site:site
        mvn site:stage
        
    - name: Create test summary
      if: always()
      run: |
        echo "## Test Results Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        if [ -d "target/surefire-reports" ]; then
          echo "### Test Reports Generated:" >> $GITHUB_STEP_SUMMARY
          find target/surefire-reports -name "*.txt" -o -name "*.xml" | while read file; do
            echo "- $(basename "$file")" >> $GITHUB_STEP_SUMMARY
          done
        fi
        
        if [ -d "target/site" ]; then
          echo "### Site Reports Generated:" >> $GITHUB_STEP_SUMMARY
          echo "- Maven Site Report" >> $GITHUB_STEP_SUMMARY
        fi
        
        if [ -d "target/site/jacoco" ]; then
          echo "### Code Coverage Report:" >> $GITHUB_STEP_SUMMARY
          echo "- JaCoCo Coverage Report" >> $GITHUB_STEP_SUMMARY
        fi
        
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "📊 Check the artifacts for detailed test reports and coverage" >> $GITHUB_STEP_SUMMARY
        
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results
        path: |
          target/surefire-reports/
          target/surefire-report/
          target/site/
        retention-days: 30
        
    - name: Upload code coverage
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: code-coverage
        path: |
          target/site/jacoco/
          target/jacoco.exec
        retention-days: 30
        
    - name: Upload JAR artifact
      uses: actions/upload-artifact@v4
      with:
        name: application-jar
        path: target/*.jar
        retention-days: 30
        
    - name: Build status check
      run: |
        if [ ${{ job.status }} == 'success' ]; then
          echo "✅ Build and tests completed successfully"
          echo "📦 JAR file, test reports, and coverage reports are available as artifacts"
        else
          echo "❌ Build or tests failed"
          exit 1
        fi